// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/contests.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/joey/wcwcpp-backend/pkg/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ContestServiceName is the fully-qualified name of the ContestService service.
	ContestServiceName = "api.v1.ContestService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ContestServiceListContestsProcedure is the fully-qualified name of the ContestService's
	// ListContests RPC.
	ContestServiceListContestsProcedure = "/api.v1.ContestService/ListContests"
	// ContestServiceCreateContestProcedure is the fully-qualified name of the ContestService's
	// CreateContest RPC.
	ContestServiceCreateContestProcedure = "/api.v1.ContestService/CreateContest"
	// ContestServiceListSubcontestsProcedure is the fully-qualified name of the ContestService's
	// ListSubcontests RPC.
	ContestServiceListSubcontestsProcedure = "/api.v1.ContestService/ListSubcontests"
	// ContestServiceCreateSubcontestProcedure is the fully-qualified name of the ContestService's
	// CreateSubcontest RPC.
	ContestServiceCreateSubcontestProcedure = "/api.v1.ContestService/CreateSubcontest"
	// ContestServiceDeleteSubcontestProcedure is the fully-qualified name of the ContestService's
	// DeleteSubcontest RPC.
	ContestServiceDeleteSubcontestProcedure = "/api.v1.ContestService/DeleteSubcontest"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	contestServiceServiceDescriptor                = v1.File_api_v1_contests_proto.Services().ByName("ContestService")
	contestServiceListContestsMethodDescriptor     = contestServiceServiceDescriptor.Methods().ByName("ListContests")
	contestServiceCreateContestMethodDescriptor    = contestServiceServiceDescriptor.Methods().ByName("CreateContest")
	contestServiceListSubcontestsMethodDescriptor  = contestServiceServiceDescriptor.Methods().ByName("ListSubcontests")
	contestServiceCreateSubcontestMethodDescriptor = contestServiceServiceDescriptor.Methods().ByName("CreateSubcontest")
	contestServiceDeleteSubcontestMethodDescriptor = contestServiceServiceDescriptor.Methods().ByName("DeleteSubcontest")
)

// ContestServiceClient is a client for the api.v1.ContestService service.
type ContestServiceClient interface {
	ListContests(context.Context, *connect.Request[v1.ListContestsRequest]) (*connect.Response[v1.ListContestsResponse], error)
	CreateContest(context.Context, *connect.Request[v1.CreateContestRequest]) (*connect.Response[v1.CreateContestResponse], error)
	ListSubcontests(context.Context, *connect.Request[v1.ListSubcontestsRequest]) (*connect.Response[v1.ListSubcontestsResponse], error)
	CreateSubcontest(context.Context, *connect.Request[v1.CreateSubcontestRequest]) (*connect.Response[v1.CreateSubcontestResponse], error)
	DeleteSubcontest(context.Context, *connect.Request[v1.DeleteSubcontestRequest]) (*connect.Response[v1.DeleteSubcontestResponse], error)
}

// NewContestServiceClient constructs a client for the api.v1.ContestService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewContestServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ContestServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &contestServiceClient{
		listContests: connect.NewClient[v1.ListContestsRequest, v1.ListContestsResponse](
			httpClient,
			baseURL+ContestServiceListContestsProcedure,
			connect.WithSchema(contestServiceListContestsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createContest: connect.NewClient[v1.CreateContestRequest, v1.CreateContestResponse](
			httpClient,
			baseURL+ContestServiceCreateContestProcedure,
			connect.WithSchema(contestServiceCreateContestMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listSubcontests: connect.NewClient[v1.ListSubcontestsRequest, v1.ListSubcontestsResponse](
			httpClient,
			baseURL+ContestServiceListSubcontestsProcedure,
			connect.WithSchema(contestServiceListSubcontestsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createSubcontest: connect.NewClient[v1.CreateSubcontestRequest, v1.CreateSubcontestResponse](
			httpClient,
			baseURL+ContestServiceCreateSubcontestProcedure,
			connect.WithSchema(contestServiceCreateSubcontestMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteSubcontest: connect.NewClient[v1.DeleteSubcontestRequest, v1.DeleteSubcontestResponse](
			httpClient,
			baseURL+ContestServiceDeleteSubcontestProcedure,
			connect.WithSchema(contestServiceDeleteSubcontestMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// contestServiceClient implements ContestServiceClient.
type contestServiceClient struct {
	listContests     *connect.Client[v1.ListContestsRequest, v1.ListContestsResponse]
	createContest    *connect.Client[v1.CreateContestRequest, v1.CreateContestResponse]
	listSubcontests  *connect.Client[v1.ListSubcontestsRequest, v1.ListSubcontestsResponse]
	createSubcontest *connect.Client[v1.CreateSubcontestRequest, v1.CreateSubcontestResponse]
	deleteSubcontest *connect.Client[v1.DeleteSubcontestRequest, v1.DeleteSubcontestResponse]
}

// ListContests calls api.v1.ContestService.ListContests.
func (c *contestServiceClient) ListContests(ctx context.Context, req *connect.Request[v1.ListContestsRequest]) (*connect.Response[v1.ListContestsResponse], error) {
	return c.listContests.CallUnary(ctx, req)
}

// CreateContest calls api.v1.ContestService.CreateContest.
func (c *contestServiceClient) CreateContest(ctx context.Context, req *connect.Request[v1.CreateContestRequest]) (*connect.Response[v1.CreateContestResponse], error) {
	return c.createContest.CallUnary(ctx, req)
}

// ListSubcontests calls api.v1.ContestService.ListSubcontests.
func (c *contestServiceClient) ListSubcontests(ctx context.Context, req *connect.Request[v1.ListSubcontestsRequest]) (*connect.Response[v1.ListSubcontestsResponse], error) {
	return c.listSubcontests.CallUnary(ctx, req)
}

// CreateSubcontest calls api.v1.ContestService.CreateSubcontest.
func (c *contestServiceClient) CreateSubcontest(ctx context.Context, req *connect.Request[v1.CreateSubcontestRequest]) (*connect.Response[v1.CreateSubcontestResponse], error) {
	return c.createSubcontest.CallUnary(ctx, req)
}

// DeleteSubcontest calls api.v1.ContestService.DeleteSubcontest.
func (c *contestServiceClient) DeleteSubcontest(ctx context.Context, req *connect.Request[v1.DeleteSubcontestRequest]) (*connect.Response[v1.DeleteSubcontestResponse], error) {
	return c.deleteSubcontest.CallUnary(ctx, req)
}

// ContestServiceHandler is an implementation of the api.v1.ContestService service.
type ContestServiceHandler interface {
	ListContests(context.Context, *connect.Request[v1.ListContestsRequest]) (*connect.Response[v1.ListContestsResponse], error)
	CreateContest(context.Context, *connect.Request[v1.CreateContestRequest]) (*connect.Response[v1.CreateContestResponse], error)
	ListSubcontests(context.Context, *connect.Request[v1.ListSubcontestsRequest]) (*connect.Response[v1.ListSubcontestsResponse], error)
	CreateSubcontest(context.Context, *connect.Request[v1.CreateSubcontestRequest]) (*connect.Response[v1.CreateSubcontestResponse], error)
	DeleteSubcontest(context.Context, *connect.Request[v1.DeleteSubcontestRequest]) (*connect.Response[v1.DeleteSubcontestResponse], error)
}

// NewContestServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewContestServiceHandler(svc ContestServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	contestServiceListContestsHandler := connect.NewUnaryHandler(
		ContestServiceListContestsProcedure,
		svc.ListContests,
		connect.WithSchema(contestServiceListContestsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	contestServiceCreateContestHandler := connect.NewUnaryHandler(
		ContestServiceCreateContestProcedure,
		svc.CreateContest,
		connect.WithSchema(contestServiceCreateContestMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	contestServiceListSubcontestsHandler := connect.NewUnaryHandler(
		ContestServiceListSubcontestsProcedure,
		svc.ListSubcontests,
		connect.WithSchema(contestServiceListSubcontestsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	contestServiceCreateSubcontestHandler := connect.NewUnaryHandler(
		ContestServiceCreateSubcontestProcedure,
		svc.CreateSubcontest,
		connect.WithSchema(contestServiceCreateSubcontestMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	contestServiceDeleteSubcontestHandler := connect.NewUnaryHandler(
		ContestServiceDeleteSubcontestProcedure,
		svc.DeleteSubcontest,
		connect.WithSchema(contestServiceDeleteSubcontestMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v1.ContestService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ContestServiceListContestsProcedure:
			contestServiceListContestsHandler.ServeHTTP(w, r)
		case ContestServiceCreateContestProcedure:
			contestServiceCreateContestHandler.ServeHTTP(w, r)
		case ContestServiceListSubcontestsProcedure:
			contestServiceListSubcontestsHandler.ServeHTTP(w, r)
		case ContestServiceCreateSubcontestProcedure:
			contestServiceCreateSubcontestHandler.ServeHTTP(w, r)
		case ContestServiceDeleteSubcontestProcedure:
			contestServiceDeleteSubcontestHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedContestServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedContestServiceHandler struct{}

func (UnimplementedContestServiceHandler) ListContests(context.Context, *connect.Request[v1.ListContestsRequest]) (*connect.Response[v1.ListContestsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.ContestService.ListContests is not implemented"))
}

func (UnimplementedContestServiceHandler) CreateContest(context.Context, *connect.Request[v1.CreateContestRequest]) (*connect.Response[v1.CreateContestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.ContestService.CreateContest is not implemented"))
}

func (UnimplementedContestServiceHandler) ListSubcontests(context.Context, *connect.Request[v1.ListSubcontestsRequest]) (*connect.Response[v1.ListSubcontestsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.ContestService.ListSubcontests is not implemented"))
}

func (UnimplementedContestServiceHandler) CreateSubcontest(context.Context, *connect.Request[v1.CreateSubcontestRequest]) (*connect.Response[v1.CreateSubcontestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.ContestService.CreateSubcontest is not implemented"))
}

func (UnimplementedContestServiceHandler) DeleteSubcontest(context.Context, *connect.Request[v1.DeleteSubcontestRequest]) (*connect.Response[v1.DeleteSubcontestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.ContestService.DeleteSubcontest is not implemented"))
}
