// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/leaderboards.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/joey/wcwcpp-backend/pkg/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LeaderboardServiceName is the fully-qualified name of the LeaderboardService service.
	LeaderboardServiceName = "api.v1.LeaderboardService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LeaderboardServiceLeaderboardProcedure is the fully-qualified name of the LeaderboardService's
	// Leaderboard RPC.
	LeaderboardServiceLeaderboardProcedure = "/api.v1.LeaderboardService/Leaderboard"
	// LeaderboardServiceSubleaderboardProcedure is the fully-qualified name of the LeaderboardService's
	// Subleaderboard RPC.
	LeaderboardServiceSubleaderboardProcedure = "/api.v1.LeaderboardService/Subleaderboard"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	leaderboardServiceServiceDescriptor              = v1.File_api_v1_leaderboards_proto.Services().ByName("LeaderboardService")
	leaderboardServiceLeaderboardMethodDescriptor    = leaderboardServiceServiceDescriptor.Methods().ByName("Leaderboard")
	leaderboardServiceSubleaderboardMethodDescriptor = leaderboardServiceServiceDescriptor.Methods().ByName("Subleaderboard")
)

// LeaderboardServiceClient is a client for the api.v1.LeaderboardService service.
type LeaderboardServiceClient interface {
	Leaderboard(context.Context, *connect.Request[v1.LeaderboardRequest]) (*connect.Response[v1.LeaderboardResponse], error)
	Subleaderboard(context.Context, *connect.Request[v1.SubleaderboardRequest]) (*connect.Response[v1.SubleaderboardResponse], error)
}

// NewLeaderboardServiceClient constructs a client for the api.v1.LeaderboardService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLeaderboardServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LeaderboardServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &leaderboardServiceClient{
		leaderboard: connect.NewClient[v1.LeaderboardRequest, v1.LeaderboardResponse](
			httpClient,
			baseURL+LeaderboardServiceLeaderboardProcedure,
			connect.WithSchema(leaderboardServiceLeaderboardMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		subleaderboard: connect.NewClient[v1.SubleaderboardRequest, v1.SubleaderboardResponse](
			httpClient,
			baseURL+LeaderboardServiceSubleaderboardProcedure,
			connect.WithSchema(leaderboardServiceSubleaderboardMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// leaderboardServiceClient implements LeaderboardServiceClient.
type leaderboardServiceClient struct {
	leaderboard    *connect.Client[v1.LeaderboardRequest, v1.LeaderboardResponse]
	subleaderboard *connect.Client[v1.SubleaderboardRequest, v1.SubleaderboardResponse]
}

// Leaderboard calls api.v1.LeaderboardService.Leaderboard.
func (c *leaderboardServiceClient) Leaderboard(ctx context.Context, req *connect.Request[v1.LeaderboardRequest]) (*connect.Response[v1.LeaderboardResponse], error) {
	return c.leaderboard.CallUnary(ctx, req)
}

// Subleaderboard calls api.v1.LeaderboardService.Subleaderboard.
func (c *leaderboardServiceClient) Subleaderboard(ctx context.Context, req *connect.Request[v1.SubleaderboardRequest]) (*connect.Response[v1.SubleaderboardResponse], error) {
	return c.subleaderboard.CallUnary(ctx, req)
}

// LeaderboardServiceHandler is an implementation of the api.v1.LeaderboardService service.
type LeaderboardServiceHandler interface {
	Leaderboard(context.Context, *connect.Request[v1.LeaderboardRequest]) (*connect.Response[v1.LeaderboardResponse], error)
	Subleaderboard(context.Context, *connect.Request[v1.SubleaderboardRequest]) (*connect.Response[v1.SubleaderboardResponse], error)
}

// NewLeaderboardServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLeaderboardServiceHandler(svc LeaderboardServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	leaderboardServiceLeaderboardHandler := connect.NewUnaryHandler(
		LeaderboardServiceLeaderboardProcedure,
		svc.Leaderboard,
		connect.WithSchema(leaderboardServiceLeaderboardMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	leaderboardServiceSubleaderboardHandler := connect.NewUnaryHandler(
		LeaderboardServiceSubleaderboardProcedure,
		svc.Subleaderboard,
		connect.WithSchema(leaderboardServiceSubleaderboardMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v1.LeaderboardService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LeaderboardServiceLeaderboardProcedure:
			leaderboardServiceLeaderboardHandler.ServeHTTP(w, r)
		case LeaderboardServiceSubleaderboardProcedure:
			leaderboardServiceSubleaderboardHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLeaderboardServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLeaderboardServiceHandler struct{}

func (UnimplementedLeaderboardServiceHandler) Leaderboard(context.Context, *connect.Request[v1.LeaderboardRequest]) (*connect.Response[v1.LeaderboardResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.LeaderboardService.Leaderboard is not implemented"))
}

func (UnimplementedLeaderboardServiceHandler) Subleaderboard(context.Context, *connect.Request[v1.SubleaderboardRequest]) (*connect.Response[v1.SubleaderboardResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.LeaderboardService.Subleaderboard is not implemented"))
}
