// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/matches.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/joey/wcwcpp-backend/pkg/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MatchServiceName is the fully-qualified name of the MatchService service.
	MatchServiceName = "api.v1.MatchService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MatchServiceListGroupMatchesProcedure is the fully-qualified name of the MatchService's
	// ListGroupMatches RPC.
	MatchServiceListGroupMatchesProcedure = "/api.v1.MatchService/ListGroupMatches"
	// MatchServiceListKnockoutMatchesProcedure is the fully-qualified name of the MatchService's
	// ListKnockoutMatches RPC.
	MatchServiceListKnockoutMatchesProcedure = "/api.v1.MatchService/ListKnockoutMatches"
	// MatchServiceCreateMatchProcedure is the fully-qualified name of the MatchService's CreateMatch
	// RPC.
	MatchServiceCreateMatchProcedure = "/api.v1.MatchService/CreateMatch"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	matchServiceServiceDescriptor                   = v1.File_api_v1_matches_proto.Services().ByName("MatchService")
	matchServiceListGroupMatchesMethodDescriptor    = matchServiceServiceDescriptor.Methods().ByName("ListGroupMatches")
	matchServiceListKnockoutMatchesMethodDescriptor = matchServiceServiceDescriptor.Methods().ByName("ListKnockoutMatches")
	matchServiceCreateMatchMethodDescriptor         = matchServiceServiceDescriptor.Methods().ByName("CreateMatch")
)

// MatchServiceClient is a client for the api.v1.MatchService service.
type MatchServiceClient interface {
	ListGroupMatches(context.Context, *connect.Request[v1.ListGroupMatchesRequest]) (*connect.Response[v1.ListGroupMatchesResponse], error)
	ListKnockoutMatches(context.Context, *connect.Request[v1.ListKnockoutMatchesRequest]) (*connect.Response[v1.ListKnockoutMatchesResponse], error)
	CreateMatch(context.Context, *connect.Request[v1.CreateMatchRequest]) (*connect.Response[v1.CreateMatchResponse], error)
}

// NewMatchServiceClient constructs a client for the api.v1.MatchService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMatchServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MatchServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &matchServiceClient{
		listGroupMatches: connect.NewClient[v1.ListGroupMatchesRequest, v1.ListGroupMatchesResponse](
			httpClient,
			baseURL+MatchServiceListGroupMatchesProcedure,
			connect.WithSchema(matchServiceListGroupMatchesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listKnockoutMatches: connect.NewClient[v1.ListKnockoutMatchesRequest, v1.ListKnockoutMatchesResponse](
			httpClient,
			baseURL+MatchServiceListKnockoutMatchesProcedure,
			connect.WithSchema(matchServiceListKnockoutMatchesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createMatch: connect.NewClient[v1.CreateMatchRequest, v1.CreateMatchResponse](
			httpClient,
			baseURL+MatchServiceCreateMatchProcedure,
			connect.WithSchema(matchServiceCreateMatchMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// matchServiceClient implements MatchServiceClient.
type matchServiceClient struct {
	listGroupMatches    *connect.Client[v1.ListGroupMatchesRequest, v1.ListGroupMatchesResponse]
	listKnockoutMatches *connect.Client[v1.ListKnockoutMatchesRequest, v1.ListKnockoutMatchesResponse]
	createMatch         *connect.Client[v1.CreateMatchRequest, v1.CreateMatchResponse]
}

// ListGroupMatches calls api.v1.MatchService.ListGroupMatches.
func (c *matchServiceClient) ListGroupMatches(ctx context.Context, req *connect.Request[v1.ListGroupMatchesRequest]) (*connect.Response[v1.ListGroupMatchesResponse], error) {
	return c.listGroupMatches.CallUnary(ctx, req)
}

// ListKnockoutMatches calls api.v1.MatchService.ListKnockoutMatches.
func (c *matchServiceClient) ListKnockoutMatches(ctx context.Context, req *connect.Request[v1.ListKnockoutMatchesRequest]) (*connect.Response[v1.ListKnockoutMatchesResponse], error) {
	return c.listKnockoutMatches.CallUnary(ctx, req)
}

// CreateMatch calls api.v1.MatchService.CreateMatch.
func (c *matchServiceClient) CreateMatch(ctx context.Context, req *connect.Request[v1.CreateMatchRequest]) (*connect.Response[v1.CreateMatchResponse], error) {
	return c.createMatch.CallUnary(ctx, req)
}

// MatchServiceHandler is an implementation of the api.v1.MatchService service.
type MatchServiceHandler interface {
	ListGroupMatches(context.Context, *connect.Request[v1.ListGroupMatchesRequest]) (*connect.Response[v1.ListGroupMatchesResponse], error)
	ListKnockoutMatches(context.Context, *connect.Request[v1.ListKnockoutMatchesRequest]) (*connect.Response[v1.ListKnockoutMatchesResponse], error)
	CreateMatch(context.Context, *connect.Request[v1.CreateMatchRequest]) (*connect.Response[v1.CreateMatchResponse], error)
}

// NewMatchServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMatchServiceHandler(svc MatchServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	matchServiceListGroupMatchesHandler := connect.NewUnaryHandler(
		MatchServiceListGroupMatchesProcedure,
		svc.ListGroupMatches,
		connect.WithSchema(matchServiceListGroupMatchesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	matchServiceListKnockoutMatchesHandler := connect.NewUnaryHandler(
		MatchServiceListKnockoutMatchesProcedure,
		svc.ListKnockoutMatches,
		connect.WithSchema(matchServiceListKnockoutMatchesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	matchServiceCreateMatchHandler := connect.NewUnaryHandler(
		MatchServiceCreateMatchProcedure,
		svc.CreateMatch,
		connect.WithSchema(matchServiceCreateMatchMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v1.MatchService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MatchServiceListGroupMatchesProcedure:
			matchServiceListGroupMatchesHandler.ServeHTTP(w, r)
		case MatchServiceListKnockoutMatchesProcedure:
			matchServiceListKnockoutMatchesHandler.ServeHTTP(w, r)
		case MatchServiceCreateMatchProcedure:
			matchServiceCreateMatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMatchServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMatchServiceHandler struct{}

func (UnimplementedMatchServiceHandler) ListGroupMatches(context.Context, *connect.Request[v1.ListGroupMatchesRequest]) (*connect.Response[v1.ListGroupMatchesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.MatchService.ListGroupMatches is not implemented"))
}

func (UnimplementedMatchServiceHandler) ListKnockoutMatches(context.Context, *connect.Request[v1.ListKnockoutMatchesRequest]) (*connect.Response[v1.ListKnockoutMatchesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.MatchService.ListKnockoutMatches is not implemented"))
}

func (UnimplementedMatchServiceHandler) CreateMatch(context.Context, *connect.Request[v1.CreateMatchRequest]) (*connect.Response[v1.CreateMatchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.MatchService.CreateMatch is not implemented"))
}
