// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/picks.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/joey/wcwcpp-backend/pkg/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PicksServiceName is the fully-qualified name of the PicksService service.
	PicksServiceName = "api.v1.PicksService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PicksServiceListGroupPicksProcedure is the fully-qualified name of the PicksService's
	// ListGroupPicks RPC.
	PicksServiceListGroupPicksProcedure = "/api.v1.PicksService/ListGroupPicks"
	// PicksServiceCreateGroupPicksProcedure is the fully-qualified name of the PicksService's
	// CreateGroupPicks RPC.
	PicksServiceCreateGroupPicksProcedure = "/api.v1.PicksService/CreateGroupPicks"
	// PicksServiceListKnockoutPicksProcedure is the fully-qualified name of the PicksService's
	// ListKnockoutPicks RPC.
	PicksServiceListKnockoutPicksProcedure = "/api.v1.PicksService/ListKnockoutPicks"
	// PicksServiceCreateKnockoutPicksProcedure is the fully-qualified name of the PicksService's
	// CreateKnockoutPicks RPC.
	PicksServiceCreateKnockoutPicksProcedure = "/api.v1.PicksService/CreateKnockoutPicks"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	picksServiceServiceDescriptor                   = v1.File_api_v1_picks_proto.Services().ByName("PicksService")
	picksServiceListGroupPicksMethodDescriptor      = picksServiceServiceDescriptor.Methods().ByName("ListGroupPicks")
	picksServiceCreateGroupPicksMethodDescriptor    = picksServiceServiceDescriptor.Methods().ByName("CreateGroupPicks")
	picksServiceListKnockoutPicksMethodDescriptor   = picksServiceServiceDescriptor.Methods().ByName("ListKnockoutPicks")
	picksServiceCreateKnockoutPicksMethodDescriptor = picksServiceServiceDescriptor.Methods().ByName("CreateKnockoutPicks")
)

// PicksServiceClient is a client for the api.v1.PicksService service.
type PicksServiceClient interface {
	ListGroupPicks(context.Context, *connect.Request[v1.GroupPicksRequest]) (*connect.Response[v1.GroupPicksResponse], error)
	CreateGroupPicks(context.Context, *connect.Request[v1.CreateGroupPicksRequest]) (*connect.Response[v1.CreateGroupPicksResponse], error)
	ListKnockoutPicks(context.Context, *connect.Request[v1.KnockoutPicksRequest]) (*connect.Response[v1.KnockoutPicksResponse], error)
	CreateKnockoutPicks(context.Context, *connect.Request[v1.CreateKnockoutPicksRequest]) (*connect.Response[v1.CreateKnockoutPicksResponse], error)
}

// NewPicksServiceClient constructs a client for the api.v1.PicksService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPicksServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PicksServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &picksServiceClient{
		listGroupPicks: connect.NewClient[v1.GroupPicksRequest, v1.GroupPicksResponse](
			httpClient,
			baseURL+PicksServiceListGroupPicksProcedure,
			connect.WithSchema(picksServiceListGroupPicksMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createGroupPicks: connect.NewClient[v1.CreateGroupPicksRequest, v1.CreateGroupPicksResponse](
			httpClient,
			baseURL+PicksServiceCreateGroupPicksProcedure,
			connect.WithSchema(picksServiceCreateGroupPicksMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listKnockoutPicks: connect.NewClient[v1.KnockoutPicksRequest, v1.KnockoutPicksResponse](
			httpClient,
			baseURL+PicksServiceListKnockoutPicksProcedure,
			connect.WithSchema(picksServiceListKnockoutPicksMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createKnockoutPicks: connect.NewClient[v1.CreateKnockoutPicksRequest, v1.CreateKnockoutPicksResponse](
			httpClient,
			baseURL+PicksServiceCreateKnockoutPicksProcedure,
			connect.WithSchema(picksServiceCreateKnockoutPicksMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// picksServiceClient implements PicksServiceClient.
type picksServiceClient struct {
	listGroupPicks      *connect.Client[v1.GroupPicksRequest, v1.GroupPicksResponse]
	createGroupPicks    *connect.Client[v1.CreateGroupPicksRequest, v1.CreateGroupPicksResponse]
	listKnockoutPicks   *connect.Client[v1.KnockoutPicksRequest, v1.KnockoutPicksResponse]
	createKnockoutPicks *connect.Client[v1.CreateKnockoutPicksRequest, v1.CreateKnockoutPicksResponse]
}

// ListGroupPicks calls api.v1.PicksService.ListGroupPicks.
func (c *picksServiceClient) ListGroupPicks(ctx context.Context, req *connect.Request[v1.GroupPicksRequest]) (*connect.Response[v1.GroupPicksResponse], error) {
	return c.listGroupPicks.CallUnary(ctx, req)
}

// CreateGroupPicks calls api.v1.PicksService.CreateGroupPicks.
func (c *picksServiceClient) CreateGroupPicks(ctx context.Context, req *connect.Request[v1.CreateGroupPicksRequest]) (*connect.Response[v1.CreateGroupPicksResponse], error) {
	return c.createGroupPicks.CallUnary(ctx, req)
}

// ListKnockoutPicks calls api.v1.PicksService.ListKnockoutPicks.
func (c *picksServiceClient) ListKnockoutPicks(ctx context.Context, req *connect.Request[v1.KnockoutPicksRequest]) (*connect.Response[v1.KnockoutPicksResponse], error) {
	return c.listKnockoutPicks.CallUnary(ctx, req)
}

// CreateKnockoutPicks calls api.v1.PicksService.CreateKnockoutPicks.
func (c *picksServiceClient) CreateKnockoutPicks(ctx context.Context, req *connect.Request[v1.CreateKnockoutPicksRequest]) (*connect.Response[v1.CreateKnockoutPicksResponse], error) {
	return c.createKnockoutPicks.CallUnary(ctx, req)
}

// PicksServiceHandler is an implementation of the api.v1.PicksService service.
type PicksServiceHandler interface {
	ListGroupPicks(context.Context, *connect.Request[v1.GroupPicksRequest]) (*connect.Response[v1.GroupPicksResponse], error)
	CreateGroupPicks(context.Context, *connect.Request[v1.CreateGroupPicksRequest]) (*connect.Response[v1.CreateGroupPicksResponse], error)
	ListKnockoutPicks(context.Context, *connect.Request[v1.KnockoutPicksRequest]) (*connect.Response[v1.KnockoutPicksResponse], error)
	CreateKnockoutPicks(context.Context, *connect.Request[v1.CreateKnockoutPicksRequest]) (*connect.Response[v1.CreateKnockoutPicksResponse], error)
}

// NewPicksServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPicksServiceHandler(svc PicksServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	picksServiceListGroupPicksHandler := connect.NewUnaryHandler(
		PicksServiceListGroupPicksProcedure,
		svc.ListGroupPicks,
		connect.WithSchema(picksServiceListGroupPicksMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	picksServiceCreateGroupPicksHandler := connect.NewUnaryHandler(
		PicksServiceCreateGroupPicksProcedure,
		svc.CreateGroupPicks,
		connect.WithSchema(picksServiceCreateGroupPicksMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	picksServiceListKnockoutPicksHandler := connect.NewUnaryHandler(
		PicksServiceListKnockoutPicksProcedure,
		svc.ListKnockoutPicks,
		connect.WithSchema(picksServiceListKnockoutPicksMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	picksServiceCreateKnockoutPicksHandler := connect.NewUnaryHandler(
		PicksServiceCreateKnockoutPicksProcedure,
		svc.CreateKnockoutPicks,
		connect.WithSchema(picksServiceCreateKnockoutPicksMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v1.PicksService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PicksServiceListGroupPicksProcedure:
			picksServiceListGroupPicksHandler.ServeHTTP(w, r)
		case PicksServiceCreateGroupPicksProcedure:
			picksServiceCreateGroupPicksHandler.ServeHTTP(w, r)
		case PicksServiceListKnockoutPicksProcedure:
			picksServiceListKnockoutPicksHandler.ServeHTTP(w, r)
		case PicksServiceCreateKnockoutPicksProcedure:
			picksServiceCreateKnockoutPicksHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPicksServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPicksServiceHandler struct{}

func (UnimplementedPicksServiceHandler) ListGroupPicks(context.Context, *connect.Request[v1.GroupPicksRequest]) (*connect.Response[v1.GroupPicksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.PicksService.ListGroupPicks is not implemented"))
}

func (UnimplementedPicksServiceHandler) CreateGroupPicks(context.Context, *connect.Request[v1.CreateGroupPicksRequest]) (*connect.Response[v1.CreateGroupPicksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.PicksService.CreateGroupPicks is not implemented"))
}

func (UnimplementedPicksServiceHandler) ListKnockoutPicks(context.Context, *connect.Request[v1.KnockoutPicksRequest]) (*connect.Response[v1.KnockoutPicksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.PicksService.ListKnockoutPicks is not implemented"))
}

func (UnimplementedPicksServiceHandler) CreateKnockoutPicks(context.Context, *connect.Request[v1.CreateKnockoutPicksRequest]) (*connect.Response[v1.CreateKnockoutPicksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.PicksService.CreateKnockoutPicks is not implemented"))
}
