//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Contests struct {
	ID                 uuid.UUID `sql:"primary_key"`
	Title              string
	Slug               string
	GroupUnlockDate    time.Time
	GroupLockDate      time.Time
	KnockoutUnlockDate time.Time
	KnockoutLockDate   time.Time
}
