//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type GroupStandings struct {
	ContestID uuid.UUID `sql:"primary_key"`
	CountryID uuid.UUID `sql:"primary_key"`
	Letter    string
	Points    int32
	Wins      int32
	Draws     int32
	Losses    int32
	Gf        int32
	Ga        int32
	Gd        int32
	Cs        int32
}
