//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type KnockoutPicks struct {
	UserID    uuid.UUID `sql:"primary_key"`
	ContestID uuid.UUID `sql:"primary_key"`
	CountryID uuid.UUID `sql:"primary_key"`
	Round     int32
}
