//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type Matches struct {
	ID                uuid.UUID `sql:"primary_key"`
	ContestID         uuid.UUID
	Country1ID        uuid.UUID
	Country2ID        uuid.UUID
	Country1Goals     *int32
	Country2Goals     *int32
	Country1Penalties *int32
	Country2Penalties *int32
}
