// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: api/v1/contests.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListContestsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListContestsRequest) Reset() {
	*x = ListContestsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_contests_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListContestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContestsRequest) ProtoMessage() {}

func (x *ListContestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_contests_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContestsRequest.ProtoReflect.Descriptor instead.
func (*ListContestsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_contests_proto_rawDescGZIP(), []int{0}
}

type ListContestsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Contests []*Contest `protobuf:"bytes,1,rep,name=contests,proto3" json:"contests,omitempty"`
}

func (x *ListContestsResponse) Reset() {
	*x = ListContestsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_contests_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListContestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContestsResponse) ProtoMessage() {}

func (x *ListContestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_contests_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContestsResponse.ProtoReflect.Descriptor instead.
func (*ListContestsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_contests_proto_rawDescGZIP(), []int{1}
}

func (x *ListContestsResponse) GetContests() []*Contest {
	if x != nil {
		return x.Contests
	}
	return nil
}

type CreateContestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title              string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Groups             []*Group               `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	GroupUnlockDate    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=group_unlock_date,json=groupUnlockDate,proto3" json:"group_unlock_date,omitempty"`
	GroupLockDate      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=group_lock_date,json=groupLockDate,proto3" json:"group_lock_date,omitempty"`
	KnockoutUnlockDate *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=knockout_unlock_date,json=knockoutUnlockDate,proto3" json:"knockout_unlock_date,omitempty"`
	KnockoutLockDate   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=knockout_lock_date,json=knockoutLockDate,proto3" json:"knockout_lock_date,omitempty"`
}

func (x *CreateContestRequest) Reset() {
	*x = CreateContestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_contests_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateContestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContestRequest) ProtoMessage() {}

func (x *CreateContestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_contests_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContestRequest.ProtoReflect.Descriptor instead.
func (*CreateContestRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_contests_proto_rawDescGZIP(), []int{2}
}

func (x *CreateContestRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateContestRequest) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *CreateContestRequest) GetGroupUnlockDate() *timestamppb.Timestamp {
	if x != nil {
		return x.GroupUnlockDate
	}
	return nil
}

func (x *CreateContestRequest) GetGroupLockDate() *timestamppb.Timestamp {
	if x != nil {
		return x.GroupLockDate
	}
	return nil
}

func (x *CreateContestRequest) GetKnockoutUnlockDate() *timestamppb.Timestamp {
	if x != nil {
		return x.KnockoutUnlockDate
	}
	return nil
}

func (x *CreateContestRequest) GetKnockoutLockDate() *timestamppb.Timestamp {
	if x != nil {
		return x.KnockoutLockDate
	}
	return nil
}

type CreateContestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateContestResponse) Reset() {
	*x = CreateContestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_contests_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateContestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContestResponse) ProtoMessage() {}

func (x *CreateContestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_contests_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContestResponse.ProtoReflect.Descriptor instead.
func (*CreateContestResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_contests_proto_rawDescGZIP(), []int{3}
}

type ListSubcontestsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContestSlug string `protobuf:"bytes,1,opt,name=contest_slug,json=contestSlug,proto3" json:"contest_slug,omitempty"`
}

func (x *ListSubcontestsRequest) Reset() {
	*x = ListSubcontestsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_contests_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSubcontestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubcontestsRequest) ProtoMessage() {}

func (x *ListSubcontestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_contests_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubcontestsRequest.ProtoReflect.Descriptor instead.
func (*ListSubcontestsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_contests_proto_rawDescGZIP(), []int{4}
}

func (x *ListSubcontestsRequest) GetContestSlug() string {
	if x != nil {
		return x.ContestSlug
	}
	return ""
}

type ListSubcontestsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subcontests []*Contest `protobuf:"bytes,1,rep,name=subcontests,proto3" json:"subcontests,omitempty"`
}

func (x *ListSubcontestsResponse) Reset() {
	*x = ListSubcontestsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_contests_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSubcontestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubcontestsResponse) ProtoMessage() {}

func (x *ListSubcontestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_contests_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubcontestsResponse.ProtoReflect.Descriptor instead.
func (*ListSubcontestsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_contests_proto_rawDescGZIP(), []int{5}
}

func (x *ListSubcontestsResponse) GetSubcontests() []*Contest {
	if x != nil {
		return x.Subcontests
	}
	return nil
}

type CreateSubcontestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContestSlug     string `protobuf:"bytes,1,opt,name=contest_slug,json=contestSlug,proto3" json:"contest_slug,omitempty"`
	SubcontestTitle string `protobuf:"bytes,2,opt,name=subcontest_title,json=subcontestTitle,proto3" json:"subcontest_title,omitempty"`
}

func (x *CreateSubcontestRequest) Reset() {
	*x = CreateSubcontestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_contests_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSubcontestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubcontestRequest) ProtoMessage() {}

func (x *CreateSubcontestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_contests_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubcontestRequest.ProtoReflect.Descriptor instead.
func (*CreateSubcontestRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_contests_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSubcontestRequest) GetContestSlug() string {
	if x != nil {
		return x.ContestSlug
	}
	return ""
}

func (x *CreateSubcontestRequest) GetSubcontestTitle() string {
	if x != nil {
		return x.SubcontestTitle
	}
	return ""
}

type CreateSubcontestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JoinCode string `protobuf:"bytes,1,opt,name=join_code,json=joinCode,proto3" json:"join_code,omitempty"`
}

func (x *CreateSubcontestResponse) Reset() {
	*x = CreateSubcontestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_contests_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSubcontestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubcontestResponse) ProtoMessage() {}

func (x *CreateSubcontestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_contests_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubcontestResponse.ProtoReflect.Descriptor instead.
func (*CreateSubcontestResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_contests_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSubcontestResponse) GetJoinCode() string {
	if x != nil {
		return x.JoinCode
	}
	return ""
}

type DeleteSubcontestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubcontestSlug string `protobuf:"bytes,1,opt,name=subcontest_slug,json=subcontestSlug,proto3" json:"subcontest_slug,omitempty"`
}

func (x *DeleteSubcontestRequest) Reset() {
	*x = DeleteSubcontestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_contests_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSubcontestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubcontestRequest) ProtoMessage() {}

func (x *DeleteSubcontestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_contests_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubcontestRequest.ProtoReflect.Descriptor instead.
func (*DeleteSubcontestRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_contests_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSubcontestRequest) GetSubcontestSlug() string {
	if x != nil {
		return x.SubcontestSlug
	}
	return ""
}

type DeleteSubcontestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteSubcontestResponse) Reset() {
	*x = DeleteSubcontestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_contests_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSubcontestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubcontestResponse) ProtoMessage() {}

func (x *DeleteSubcontestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_contests_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubcontestResponse.ProtoReflect.Descriptor instead.
func (*DeleteSubcontestResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_contests_proto_rawDescGZIP(), []int{9}
}

type JoinSubcontestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JoinCode string `protobuf:"bytes,1,opt,name=join_code,json=joinCode,proto3" json:"join_code,omitempty"`
}

func (x *JoinSubcontestRequest) Reset() {
	*x = JoinSubcontestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_contests_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinSubcontestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSubcontestRequest) ProtoMessage() {}

func (x *JoinSubcontestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_contests_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSubcontestRequest.ProtoReflect.Descriptor instead.
func (*JoinSubcontestRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_contests_proto_rawDescGZIP(), []int{10}
}

func (x *JoinSubcontestRequest) GetJoinCode() string {
	if x != nil {
		return x.JoinCode
	}
	return ""
}

type JoinSubcontestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JoinSubcontestResponse) Reset() {
	*x = JoinSubcontestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_contests_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinSubcontestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSubcontestResponse) ProtoMessage() {}

func (x *JoinSubcontestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_contests_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSubcontestResponse.ProtoReflect.Descriptor instead.
func (*JoinSubcontestResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_contests_proto_rawDescGZIP(), []int{11}
}

var File_api_v1_contests_proto protoreflect.FileDescriptor

var file_api_v1_contests_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a,
	0x12, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x15, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x43, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2b, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x73, 0x74, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x22, 0x83, 0x03,
	0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x31, 0x0a, 0x06,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x0a, 0xba, 0x48, 0x07,
	0x92, 0x01, 0x04, 0x08, 0x0c, 0x10, 0x0c, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12,
	0x46, 0x0a, 0x11, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x5f,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x55, 0x6e, 0x6c,
	0x6f, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x65, 0x12, 0x42, 0x0a, 0x0f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x4c, 0x6f, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x65, 0x12, 0x4c, 0x0a, 0x14, 0x6b,
	0x6e, 0x6f, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x5f, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x12, 0x6b, 0x6e, 0x6f, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x55,
	0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x65, 0x12, 0x48, 0x0a, 0x12, 0x6b, 0x6e, 0x6f,
	0x63, 0x6b, 0x6f, 0x75, 0x74, 0x5f, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x10, 0x6b, 0x6e, 0x6f, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x4c, 0x6f, 0x63, 0x6b, 0x44,
	0x61, 0x74, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3b, 0x0a, 0x16,
	0x4c, 0x69, 0x73, 0x74, 0x53, 0x75, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73,
	0x74, 0x5f, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x73, 0x74, 0x53, 0x6c, 0x75, 0x67, 0x22, 0x4c, 0x0a, 0x17, 0x4c, 0x69, 0x73,
	0x74, 0x53, 0x75, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0b, 0x73, 0x75, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x73, 0x75, 0x62, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x22, 0x67, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x53, 0x75, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x73, 0x6c,
	0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73,
	0x74, 0x53, 0x6c, 0x75, 0x67, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x75, 0x62, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x73, 0x74, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x73, 0x75, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x22, 0x37, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6a, 0x6f, 0x69, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x42, 0x0a, 0x17, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x75, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x75, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x73, 0x74, 0x5f, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73,
	0x75, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x53, 0x6c, 0x75, 0x67, 0x22, 0x1a, 0x0a,
	0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x75, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x34, 0x0a, 0x15, 0x4a, 0x6f, 0x69,
	0x6e, 0x53, 0x75, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6a, 0x6f, 0x69, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x22,
	0x18, 0x0a, 0x16, 0x4a, 0x6f, 0x69, 0x6e, 0x53, 0x75, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xab, 0x03, 0x0a, 0x0e, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x0c,
	0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x12, 0x1b, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x73,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x75, 0x62,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x75, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x75, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x10, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x75, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x75,
	0x62, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x55, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x75, 0x62, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x53, 0x75, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x75, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x6f, 0x65, 0x79, 0x2f, 0x77, 0x63, 0x77, 0x63, 0x70,
	0x70, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_contests_proto_rawDescOnce sync.Once
	file_api_v1_contests_proto_rawDescData = file_api_v1_contests_proto_rawDesc
)

func file_api_v1_contests_proto_rawDescGZIP() []byte {
	file_api_v1_contests_proto_rawDescOnce.Do(func() {
		file_api_v1_contests_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_contests_proto_rawDescData)
	})
	return file_api_v1_contests_proto_rawDescData
}

var file_api_v1_contests_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_v1_contests_proto_goTypes = []interface{}{
	(*ListContestsRequest)(nil),      // 0: api.v1.ListContestsRequest
	(*ListContestsResponse)(nil),     // 1: api.v1.ListContestsResponse
	(*CreateContestRequest)(nil),     // 2: api.v1.CreateContestRequest
	(*CreateContestResponse)(nil),    // 3: api.v1.CreateContestResponse
	(*ListSubcontestsRequest)(nil),   // 4: api.v1.ListSubcontestsRequest
	(*ListSubcontestsResponse)(nil),  // 5: api.v1.ListSubcontestsResponse
	(*CreateSubcontestRequest)(nil),  // 6: api.v1.CreateSubcontestRequest
	(*CreateSubcontestResponse)(nil), // 7: api.v1.CreateSubcontestResponse
	(*DeleteSubcontestRequest)(nil),  // 8: api.v1.DeleteSubcontestRequest
	(*DeleteSubcontestResponse)(nil), // 9: api.v1.DeleteSubcontestResponse
	(*JoinSubcontestRequest)(nil),    // 10: api.v1.JoinSubcontestRequest
	(*JoinSubcontestResponse)(nil),   // 11: api.v1.JoinSubcontestResponse
	(*Contest)(nil),                  // 12: api.v1.Contest
	(*Group)(nil),                    // 13: api.v1.Group
	(*timestamppb.Timestamp)(nil),    // 14: google.protobuf.Timestamp
}
var file_api_v1_contests_proto_depIdxs = []int32{
	12, // 0: api.v1.ListContestsResponse.contests:type_name -> api.v1.Contest
	13, // 1: api.v1.CreateContestRequest.groups:type_name -> api.v1.Group
	14, // 2: api.v1.CreateContestRequest.group_unlock_date:type_name -> google.protobuf.Timestamp
	14, // 3: api.v1.CreateContestRequest.group_lock_date:type_name -> google.protobuf.Timestamp
	14, // 4: api.v1.CreateContestRequest.knockout_unlock_date:type_name -> google.protobuf.Timestamp
	14, // 5: api.v1.CreateContestRequest.knockout_lock_date:type_name -> google.protobuf.Timestamp
	12, // 6: api.v1.ListSubcontestsResponse.subcontests:type_name -> api.v1.Contest
	0,  // 7: api.v1.ContestService.ListContests:input_type -> api.v1.ListContestsRequest
	2,  // 8: api.v1.ContestService.CreateContest:input_type -> api.v1.CreateContestRequest
	4,  // 9: api.v1.ContestService.ListSubcontests:input_type -> api.v1.ListSubcontestsRequest
	6,  // 10: api.v1.ContestService.CreateSubcontest:input_type -> api.v1.CreateSubcontestRequest
	8,  // 11: api.v1.ContestService.DeleteSubcontest:input_type -> api.v1.DeleteSubcontestRequest
	1,  // 12: api.v1.ContestService.ListContests:output_type -> api.v1.ListContestsResponse
	3,  // 13: api.v1.ContestService.CreateContest:output_type -> api.v1.CreateContestResponse
	5,  // 14: api.v1.ContestService.ListSubcontests:output_type -> api.v1.ListSubcontestsResponse
	7,  // 15: api.v1.ContestService.CreateSubcontest:output_type -> api.v1.CreateSubcontestResponse
	9,  // 16: api.v1.ContestService.DeleteSubcontest:output_type -> api.v1.DeleteSubcontestResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_v1_contests_proto_init() }
func file_api_v1_contests_proto_init() {
	if File_api_v1_contests_proto != nil {
		return
	}
	file_api_v1_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_v1_contests_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListContestsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_contests_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListContestsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_contests_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateContestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_contests_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateContestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_contests_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSubcontestsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_contests_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSubcontestsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_contests_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSubcontestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_contests_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSubcontestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_contests_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSubcontestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_contests_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSubcontestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_contests_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinSubcontestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_contests_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinSubcontestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_contests_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_contests_proto_goTypes,
		DependencyIndexes: file_api_v1_contests_proto_depIdxs,
		MessageInfos:      file_api_v1_contests_proto_msgTypes,
	}.Build()
	File_api_v1_contests_proto = out.File
	file_api_v1_contests_proto_rawDesc = nil
	file_api_v1_contests_proto_goTypes = nil
	file_api_v1_contests_proto_depIdxs = nil
}
