// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: api/v1/picks.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupPicksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContestSlug string `protobuf:"bytes,1,opt,name=contest_slug,json=contestSlug,proto3" json:"contest_slug,omitempty"`
}

func (x *GroupPicksRequest) Reset() {
	*x = GroupPicksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_picks_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupPicksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPicksRequest) ProtoMessage() {}

func (x *GroupPicksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_picks_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPicksRequest.ProtoReflect.Descriptor instead.
func (*GroupPicksRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_picks_proto_rawDescGZIP(), []int{0}
}

func (x *GroupPicksRequest) GetContestSlug() string {
	if x != nil {
		return x.ContestSlug
	}
	return ""
}

type GroupPicksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Picks []*GroupPick `protobuf:"bytes,1,rep,name=picks,proto3" json:"picks,omitempty"`
}

func (x *GroupPicksResponse) Reset() {
	*x = GroupPicksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_picks_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupPicksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPicksResponse) ProtoMessage() {}

func (x *GroupPicksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_picks_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPicksResponse.ProtoReflect.Descriptor instead.
func (*GroupPicksResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_picks_proto_rawDescGZIP(), []int{1}
}

func (x *GroupPicksResponse) GetPicks() []*GroupPick {
	if x != nil {
		return x.Picks
	}
	return nil
}

type CreateGroupPicksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContestSlug string     `protobuf:"bytes,1,opt,name=contest_slug,json=contestSlug,proto3" json:"contest_slug,omitempty"`
	Pick        *GroupPick `protobuf:"bytes,2,opt,name=pick,proto3" json:"pick,omitempty"`
}

func (x *CreateGroupPicksRequest) Reset() {
	*x = CreateGroupPicksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_picks_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGroupPicksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupPicksRequest) ProtoMessage() {}

func (x *CreateGroupPicksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_picks_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupPicksRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupPicksRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_picks_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGroupPicksRequest) GetContestSlug() string {
	if x != nil {
		return x.ContestSlug
	}
	return ""
}

func (x *CreateGroupPicksRequest) GetPick() *GroupPick {
	if x != nil {
		return x.Pick
	}
	return nil
}

type CreateGroupPicksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateGroupPicksResponse) Reset() {
	*x = CreateGroupPicksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_picks_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGroupPicksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupPicksResponse) ProtoMessage() {}

func (x *CreateGroupPicksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_picks_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupPicksResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupPicksResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_picks_proto_rawDescGZIP(), []int{3}
}

type KnockoutPicksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContestSlug string `protobuf:"bytes,1,opt,name=contest_slug,json=contestSlug,proto3" json:"contest_slug,omitempty"`
}

func (x *KnockoutPicksRequest) Reset() {
	*x = KnockoutPicksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_picks_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KnockoutPicksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnockoutPicksRequest) ProtoMessage() {}

func (x *KnockoutPicksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_picks_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnockoutPicksRequest.ProtoReflect.Descriptor instead.
func (*KnockoutPicksRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_picks_proto_rawDescGZIP(), []int{4}
}

func (x *KnockoutPicksRequest) GetContestSlug() string {
	if x != nil {
		return x.ContestSlug
	}
	return ""
}

type KnockoutPicksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Picks []*KnockoutPick `protobuf:"bytes,1,rep,name=picks,proto3" json:"picks,omitempty"`
}

func (x *KnockoutPicksResponse) Reset() {
	*x = KnockoutPicksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_picks_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KnockoutPicksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnockoutPicksResponse) ProtoMessage() {}

func (x *KnockoutPicksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_picks_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnockoutPicksResponse.ProtoReflect.Descriptor instead.
func (*KnockoutPicksResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_picks_proto_rawDescGZIP(), []int{5}
}

func (x *KnockoutPicksResponse) GetPicks() []*KnockoutPick {
	if x != nil {
		return x.Picks
	}
	return nil
}

type CreateKnockoutPicksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContestSlug string        `protobuf:"bytes,1,opt,name=contest_slug,json=contestSlug,proto3" json:"contest_slug,omitempty"`
	Pick        *KnockoutPick `protobuf:"bytes,2,opt,name=pick,proto3" json:"pick,omitempty"`
}

func (x *CreateKnockoutPicksRequest) Reset() {
	*x = CreateKnockoutPicksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_picks_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKnockoutPicksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnockoutPicksRequest) ProtoMessage() {}

func (x *CreateKnockoutPicksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_picks_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnockoutPicksRequest.ProtoReflect.Descriptor instead.
func (*CreateKnockoutPicksRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_picks_proto_rawDescGZIP(), []int{6}
}

func (x *CreateKnockoutPicksRequest) GetContestSlug() string {
	if x != nil {
		return x.ContestSlug
	}
	return ""
}

func (x *CreateKnockoutPicksRequest) GetPick() *KnockoutPick {
	if x != nil {
		return x.Pick
	}
	return nil
}

type CreateKnockoutPicksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateKnockoutPicksResponse) Reset() {
	*x = CreateKnockoutPicksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_picks_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKnockoutPicksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnockoutPicksResponse) ProtoMessage() {}

func (x *CreateKnockoutPicksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_picks_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnockoutPicksResponse.ProtoReflect.Descriptor instead.
func (*CreateKnockoutPicksResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_picks_proto_rawDescGZIP(), []int{7}
}

var File_api_v1_picks_proto protoreflect.FileDescriptor

var file_api_v1_picks_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x69, 0x63, 0x6b, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x12, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x36, 0x0a, 0x11, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x50, 0x69, 0x63, 0x6b, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74,
	0x5f, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x73, 0x74, 0x53, 0x6c, 0x75, 0x67, 0x22, 0x3d, 0x0a, 0x12, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x50, 0x69, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27,
	0x0a, 0x05, 0x70, 0x69, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x50, 0x69, 0x63, 0x6b,
	0x52, 0x05, 0x70, 0x69, 0x63, 0x6b, 0x73, 0x22, 0x63, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x50, 0x69, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x73, 0x6c,
	0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73,
	0x74, 0x53, 0x6c, 0x75, 0x67, 0x12, 0x25, 0x0a, 0x04, 0x70, 0x69, 0x63, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x50, 0x69, 0x63, 0x6b, 0x52, 0x04, 0x70, 0x69, 0x63, 0x6b, 0x22, 0x1a, 0x0a, 0x18,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x50, 0x69, 0x63, 0x6b, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x39, 0x0a, 0x14, 0x4b, 0x6e, 0x6f, 0x63,
	0x6b, 0x6f, 0x75, 0x74, 0x50, 0x69, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x73, 0x6c, 0x75, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x53,
	0x6c, 0x75, 0x67, 0x22, 0x43, 0x0a, 0x15, 0x4b, 0x6e, 0x6f, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x50,
	0x69, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x05,
	0x70, 0x69, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x6e, 0x6f, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x50, 0x69, 0x63,
	0x6b, 0x52, 0x05, 0x70, 0x69, 0x63, 0x6b, 0x73, 0x22, 0x69, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x50, 0x69, 0x63, 0x6b, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73,
	0x74, 0x5f, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x73, 0x74, 0x53, 0x6c, 0x75, 0x67, 0x12, 0x28, 0x0a, 0x04, 0x70, 0x69, 0x63,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x4b, 0x6e, 0x6f, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x50, 0x69, 0x63, 0x6b, 0x52, 0x04, 0x70,
	0x69, 0x63, 0x6b, 0x22, 0x1d, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x6e, 0x6f,
	0x63, 0x6b, 0x6f, 0x75, 0x74, 0x50, 0x69, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0xe0, 0x02, 0x0a, 0x0c, 0x50, 0x69, 0x63, 0x6b, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x50, 0x69, 0x63, 0x6b, 0x73, 0x12, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x50, 0x69, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x50,
	0x69, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x10,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x50, 0x69, 0x63, 0x6b, 0x73,
	0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x50, 0x69, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x50, 0x69, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x6e, 0x6f, 0x63, 0x6b,
	0x6f, 0x75, 0x74, 0x50, 0x69, 0x63, 0x6b, 0x73, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x4b, 0x6e, 0x6f, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x50, 0x69, 0x63, 0x6b, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x4b, 0x6e, 0x6f, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x50, 0x69, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b,
	0x6e, 0x6f, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x50, 0x69, 0x63, 0x6b, 0x73, 0x12, 0x22, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x63,
	0x6b, 0x6f, 0x75, 0x74, 0x50, 0x69, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4b, 0x6e, 0x6f, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x50, 0x69, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x6f, 0x65, 0x79, 0x2f, 0x77, 0x63, 0x77, 0x63, 0x70, 0x70, 0x2d,
	0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_picks_proto_rawDescOnce sync.Once
	file_api_v1_picks_proto_rawDescData = file_api_v1_picks_proto_rawDesc
)

func file_api_v1_picks_proto_rawDescGZIP() []byte {
	file_api_v1_picks_proto_rawDescOnce.Do(func() {
		file_api_v1_picks_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_picks_proto_rawDescData)
	})
	return file_api_v1_picks_proto_rawDescData
}

var file_api_v1_picks_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_v1_picks_proto_goTypes = []interface{}{
	(*GroupPicksRequest)(nil),           // 0: api.v1.GroupPicksRequest
	(*GroupPicksResponse)(nil),          // 1: api.v1.GroupPicksResponse
	(*CreateGroupPicksRequest)(nil),     // 2: api.v1.CreateGroupPicksRequest
	(*CreateGroupPicksResponse)(nil),    // 3: api.v1.CreateGroupPicksResponse
	(*KnockoutPicksRequest)(nil),        // 4: api.v1.KnockoutPicksRequest
	(*KnockoutPicksResponse)(nil),       // 5: api.v1.KnockoutPicksResponse
	(*CreateKnockoutPicksRequest)(nil),  // 6: api.v1.CreateKnockoutPicksRequest
	(*CreateKnockoutPicksResponse)(nil), // 7: api.v1.CreateKnockoutPicksResponse
	(*GroupPick)(nil),                   // 8: api.v1.GroupPick
	(*KnockoutPick)(nil),                // 9: api.v1.KnockoutPick
}
var file_api_v1_picks_proto_depIdxs = []int32{
	8, // 0: api.v1.GroupPicksResponse.picks:type_name -> api.v1.GroupPick
	8, // 1: api.v1.CreateGroupPicksRequest.pick:type_name -> api.v1.GroupPick
	9, // 2: api.v1.KnockoutPicksResponse.picks:type_name -> api.v1.KnockoutPick
	9, // 3: api.v1.CreateKnockoutPicksRequest.pick:type_name -> api.v1.KnockoutPick
	0, // 4: api.v1.PicksService.ListGroupPicks:input_type -> api.v1.GroupPicksRequest
	2, // 5: api.v1.PicksService.CreateGroupPicks:input_type -> api.v1.CreateGroupPicksRequest
	4, // 6: api.v1.PicksService.ListKnockoutPicks:input_type -> api.v1.KnockoutPicksRequest
	6, // 7: api.v1.PicksService.CreateKnockoutPicks:input_type -> api.v1.CreateKnockoutPicksRequest
	1, // 8: api.v1.PicksService.ListGroupPicks:output_type -> api.v1.GroupPicksResponse
	3, // 9: api.v1.PicksService.CreateGroupPicks:output_type -> api.v1.CreateGroupPicksResponse
	5, // 10: api.v1.PicksService.ListKnockoutPicks:output_type -> api.v1.KnockoutPicksResponse
	7, // 11: api.v1.PicksService.CreateKnockoutPicks:output_type -> api.v1.CreateKnockoutPicksResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_v1_picks_proto_init() }
func file_api_v1_picks_proto_init() {
	if File_api_v1_picks_proto != nil {
		return
	}
	file_api_v1_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_v1_picks_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupPicksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_picks_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupPicksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_picks_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGroupPicksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_picks_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGroupPicksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_picks_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KnockoutPicksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_picks_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KnockoutPicksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_picks_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKnockoutPicksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_picks_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKnockoutPicksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_picks_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_picks_proto_goTypes,
		DependencyIndexes: file_api_v1_picks_proto_depIdxs,
		MessageInfos:      file_api_v1_picks_proto_msgTypes,
	}.Build()
	File_api_v1_picks_proto = out.File
	file_api_v1_picks_proto_rawDesc = nil
	file_api_v1_picks_proto_goTypes = nil
	file_api_v1_picks_proto_depIdxs = nil
}
