// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: api/v1/types.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Contest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title  string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Slug   string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Active bool   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
}

func (x *Contest) Reset() {
	*x = Contest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Contest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contest) ProtoMessage() {}

func (x *Contest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contest.ProtoReflect.Descriptor instead.
func (*Contest) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Contest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Contest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Contest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type Country struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	FullName string `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
}

func (x *Country) Reset() {
	*x = Country{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Country) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Country) ProtoMessage() {}

func (x *Country) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Country.ProtoReflect.Descriptor instead.
func (*Country) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *Country) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Country) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type Group struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Letter    string     `protobuf:"bytes,1,opt,name=letter,proto3" json:"letter,omitempty"`
	Countries []*Country `protobuf:"bytes,2,rep,name=countries,proto3" json:"countries,omitempty"`
}

func (x *Group) Reset() {
	*x = Group{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *Group) GetLetter() string {
	if x != nil {
		return x.Letter
	}
	return ""
}

func (x *Group) GetCountries() []*Country {
	if x != nil {
		return x.Countries
	}
	return nil
}

type GroupPick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group          *Group `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	ExtraQualifier bool   `protobuf:"varint,2,opt,name=extra_qualifier,json=extraQualifier,proto3" json:"extra_qualifier,omitempty"`
}

func (x *GroupPick) Reset() {
	*x = GroupPick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupPick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPick) ProtoMessage() {}

func (x *GroupPick) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPick.ProtoReflect.Descriptor instead.
func (*GroupPick) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *GroupPick) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupPick) GetExtraQualifier() bool {
	if x != nil {
		return x.ExtraQualifier
	}
	return false
}

type KnockoutEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Country *Country `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Round   int64    `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
}

func (x *KnockoutEntry) Reset() {
	*x = KnockoutEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_types_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KnockoutEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnockoutEntry) ProtoMessage() {}

func (x *KnockoutEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnockoutEntry.ProtoReflect.Descriptor instead.
func (*KnockoutEntry) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *KnockoutEntry) GetCountry() *Country {
	if x != nil {
		return x.Country
	}
	return nil
}

func (x *KnockoutEntry) GetRound() int64 {
	if x != nil {
		return x.Round
	}
	return 0
}

type KnockoutPick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*KnockoutEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *KnockoutPick) Reset() {
	*x = KnockoutPick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_types_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KnockoutPick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnockoutPick) ProtoMessage() {}

func (x *KnockoutPick) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnockoutPick.ProtoReflect.Descriptor instead.
func (*KnockoutPick) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *KnockoutPick) GetEntries() []*KnockoutEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Match struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Country1          *Country `protobuf:"bytes,1,opt,name=country1,proto3,oneof" json:"country1,omitempty"`
	Country2          *Country `protobuf:"bytes,2,opt,name=country2,proto3,oneof" json:"country2,omitempty"`
	Country1Goals     *int64   `protobuf:"varint,4,opt,name=country1_goals,json=country1Goals,proto3,oneof" json:"country1_goals,omitempty"`
	Country2Goals     *int64   `protobuf:"varint,5,opt,name=country2_goals,json=country2Goals,proto3,oneof" json:"country2_goals,omitempty"`
	Country1Penalties *int64   `protobuf:"varint,6,opt,name=country1_penalties,json=country1Penalties,proto3,oneof" json:"country1_penalties,omitempty"`
	Country2Penalties *int64   `protobuf:"varint,7,opt,name=country2_penalties,json=country2Penalties,proto3,oneof" json:"country2_penalties,omitempty"`
}

func (x *Match) Reset() {
	*x = Match{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_types_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *Match) GetCountry1() *Country {
	if x != nil {
		return x.Country1
	}
	return nil
}

func (x *Match) GetCountry2() *Country {
	if x != nil {
		return x.Country2
	}
	return nil
}

func (x *Match) GetCountry1Goals() int64 {
	if x != nil && x.Country1Goals != nil {
		return *x.Country1Goals
	}
	return 0
}

func (x *Match) GetCountry2Goals() int64 {
	if x != nil && x.Country2Goals != nil {
		return *x.Country2Goals
	}
	return 0
}

func (x *Match) GetCountry1Penalties() int64 {
	if x != nil && x.Country1Penalties != nil {
		return *x.Country1Penalties
	}
	return 0
}

func (x *Match) GetCountry2Penalties() int64 {
	if x != nil && x.Country2Penalties != nil {
		return *x.Country2Penalties
	}
	return 0
}

type LeaderboardEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Score int64  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_types_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *LeaderboardEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LeaderboardEntry) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_api_v1_types_proto protoreflect.FileDescriptor

var file_api_v1_types_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x62, 0x75,
	0x66, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x07, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c,
	0x75, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x3a, 0x0a, 0x07, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x5a, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x6c,
	0x65, 0x74, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x65, 0x74,
	0x74, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x42, 0x0a, 0xba, 0x48, 0x07, 0x92, 0x01, 0x04, 0x08,
	0x04, 0x10, 0x04, 0x52, 0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x59,
	0x0a, 0x09, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x50, 0x69, 0x63, 0x6b, 0x12, 0x23, 0x0a, 0x05, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x12, 0x27, 0x0a, 0x0f, 0x65, 0x78, 0x74, 0x72, 0x61, 0x5f, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x65, 0x78, 0x74, 0x72, 0x61,
	0x51, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x50, 0x0a, 0x0d, 0x4b, 0x6e, 0x6f,
	0x63, 0x6b, 0x6f, 0x75, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x29, 0x0a, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x4b, 0x0a, 0x0c, 0x4b,
	0x6e, 0x6f, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x50, 0x69, 0x63, 0x6b, 0x12, 0x3b, 0x0a, 0x07, 0x65,
	0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x6e, 0x6f, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x42, 0x0a, 0xba, 0x48, 0x07, 0x92, 0x01, 0x04, 0x08, 0x20, 0x10, 0x20, 0x52,
	0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x99, 0x03, 0x0a, 0x05, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x12, 0x30, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x31, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x48, 0x00, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x31, 0x88, 0x01, 0x01, 0x12, 0x30, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x32,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x48, 0x01, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x32, 0x88, 0x01, 0x01, 0x12, 0x2a, 0x0a, 0x0e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x31, 0x5f, 0x67, 0x6f, 0x61, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x48, 0x02,
	0x52, 0x0d, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x31, 0x47, 0x6f, 0x61, 0x6c, 0x73, 0x88,
	0x01, 0x01, 0x12, 0x2a, 0x0a, 0x0e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x32, 0x5f, 0x67,
	0x6f, 0x61, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x48, 0x03, 0x52, 0x0d, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x32, 0x47, 0x6f, 0x61, 0x6c, 0x73, 0x88, 0x01, 0x01, 0x12, 0x32,
	0x0a, 0x12, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x31, 0x5f, 0x70, 0x65, 0x6e, 0x61, 0x6c,
	0x74, 0x69, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x48, 0x04, 0x52, 0x11, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x31, 0x50, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x69, 0x65, 0x73, 0x88,
	0x01, 0x01, 0x12, 0x32, 0x0a, 0x12, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x32, 0x5f, 0x70,
	0x65, 0x6e, 0x61, 0x6c, 0x74, 0x69, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x48, 0x05,
	0x52, 0x11, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x32, 0x50, 0x65, 0x6e, 0x61, 0x6c, 0x74,
	0x69, 0x65, 0x73, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x31, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x32,
	0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x31, 0x5f, 0x67, 0x6f,
	0x61, 0x6c, 0x73, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x32,
	0x5f, 0x67, 0x6f, 0x61, 0x6c, 0x73, 0x42, 0x15, 0x0a, 0x13, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x31, 0x5f, 0x70, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x69, 0x65, 0x73, 0x42, 0x15, 0x0a,
	0x13, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x32, 0x5f, 0x70, 0x65, 0x6e, 0x61, 0x6c,
	0x74, 0x69, 0x65, 0x73, 0x22, 0x3c, 0x0a, 0x10, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6a, 0x6f, 0x65, 0x79, 0x2f, 0x77, 0x63, 0x77, 0x63, 0x70, 0x70, 0x2d, 0x62, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_types_proto_rawDescOnce sync.Once
	file_api_v1_types_proto_rawDescData = file_api_v1_types_proto_rawDesc
)

func file_api_v1_types_proto_rawDescGZIP() []byte {
	file_api_v1_types_proto_rawDescOnce.Do(func() {
		file_api_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_types_proto_rawDescData)
	})
	return file_api_v1_types_proto_rawDescData
}

var file_api_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_v1_types_proto_goTypes = []interface{}{
	(*Contest)(nil),          // 0: api.v1.Contest
	(*Country)(nil),          // 1: api.v1.Country
	(*Group)(nil),            // 2: api.v1.Group
	(*GroupPick)(nil),        // 3: api.v1.GroupPick
	(*KnockoutEntry)(nil),    // 4: api.v1.KnockoutEntry
	(*KnockoutPick)(nil),     // 5: api.v1.KnockoutPick
	(*Match)(nil),            // 6: api.v1.Match
	(*LeaderboardEntry)(nil), // 7: api.v1.LeaderboardEntry
}
var file_api_v1_types_proto_depIdxs = []int32{
	1, // 0: api.v1.Group.countries:type_name -> api.v1.Country
	2, // 1: api.v1.GroupPick.group:type_name -> api.v1.Group
	1, // 2: api.v1.KnockoutEntry.country:type_name -> api.v1.Country
	4, // 3: api.v1.KnockoutPick.entries:type_name -> api.v1.KnockoutEntry
	1, // 4: api.v1.Match.country1:type_name -> api.v1.Country
	1, // 5: api.v1.Match.country2:type_name -> api.v1.Country
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_v1_types_proto_init() }
func file_api_v1_types_proto_init() {
	if File_api_v1_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Contest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Country); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Group); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_types_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupPick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_types_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KnockoutEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_types_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KnockoutPick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_types_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Match); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_types_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaderboardEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_v1_types_proto_msgTypes[6].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_types_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_types_proto_goTypes,
		DependencyIndexes: file_api_v1_types_proto_depIdxs,
		MessageInfos:      file_api_v1_types_proto_msgTypes,
	}.Build()
	File_api_v1_types_proto = out.File
	file_api_v1_types_proto_rawDesc = nil
	file_api_v1_types_proto_goTypes = nil
	file_api_v1_types_proto_depIdxs = nil
}
