//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Contests = newContestsTable("public", "contests", "")

type contestsTable struct {
	postgres.Table

	// Columns
	ID                 postgres.ColumnString
	Title              postgres.ColumnString
	Slug               postgres.ColumnString
	GroupUnlockDate    postgres.ColumnTimestampz
	GroupLockDate      postgres.ColumnTimestampz
	KnockoutUnlockDate postgres.ColumnTimestampz
	KnockoutLockDate   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ContestsTable struct {
	contestsTable

	EXCLUDED contestsTable
}

// AS creates new ContestsTable with assigned alias
func (a ContestsTable) AS(alias string) *ContestsTable {
	return newContestsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ContestsTable with assigned schema name
func (a ContestsTable) FromSchema(schemaName string) *ContestsTable {
	return newContestsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ContestsTable with assigned table prefix
func (a ContestsTable) WithPrefix(prefix string) *ContestsTable {
	return newContestsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ContestsTable with assigned table suffix
func (a ContestsTable) WithSuffix(suffix string) *ContestsTable {
	return newContestsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newContestsTable(schemaName, tableName, alias string) *ContestsTable {
	return &ContestsTable{
		contestsTable: newContestsTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newContestsTableImpl("", "excluded", ""),
	}
}

func newContestsTableImpl(schemaName, tableName, alias string) contestsTable {
	var (
		IDColumn                 = postgres.StringColumn("id")
		TitleColumn              = postgres.StringColumn("title")
		SlugColumn               = postgres.StringColumn("slug")
		GroupUnlockDateColumn    = postgres.TimestampzColumn("group_unlock_date")
		GroupLockDateColumn      = postgres.TimestampzColumn("group_lock_date")
		KnockoutUnlockDateColumn = postgres.TimestampzColumn("knockout_unlock_date")
		KnockoutLockDateColumn   = postgres.TimestampzColumn("knockout_lock_date")
		allColumns               = postgres.ColumnList{IDColumn, TitleColumn, SlugColumn, GroupUnlockDateColumn, GroupLockDateColumn, KnockoutUnlockDateColumn, KnockoutLockDateColumn}
		mutableColumns           = postgres.ColumnList{TitleColumn, SlugColumn, GroupUnlockDateColumn, GroupLockDateColumn, KnockoutUnlockDateColumn, KnockoutLockDateColumn}
		defaultColumns           = postgres.ColumnList{IDColumn}
	)

	return contestsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                 IDColumn,
		Title:              TitleColumn,
		Slug:               SlugColumn,
		GroupUnlockDate:    GroupUnlockDateColumn,
		GroupLockDate:      GroupLockDateColumn,
		KnockoutUnlockDate: KnockoutUnlockDateColumn,
		KnockoutLockDate:   KnockoutLockDateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
