//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ContestStandings = newContestStandingsTable("public", "contest_standings", "")

type contestStandingsTable struct {
	postgres.Table

	// Columns
	ContestID postgres.ColumnString
	UserID    postgres.ColumnString
	Score     postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ContestStandingsTable struct {
	contestStandingsTable

	EXCLUDED contestStandingsTable
}

// AS creates new ContestStandingsTable with assigned alias
func (a ContestStandingsTable) AS(alias string) *ContestStandingsTable {
	return newContestStandingsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ContestStandingsTable with assigned schema name
func (a ContestStandingsTable) FromSchema(schemaName string) *ContestStandingsTable {
	return newContestStandingsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ContestStandingsTable with assigned table prefix
func (a ContestStandingsTable) WithPrefix(prefix string) *ContestStandingsTable {
	return newContestStandingsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ContestStandingsTable with assigned table suffix
func (a ContestStandingsTable) WithSuffix(suffix string) *ContestStandingsTable {
	return newContestStandingsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newContestStandingsTable(schemaName, tableName, alias string) *ContestStandingsTable {
	return &ContestStandingsTable{
		contestStandingsTable: newContestStandingsTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newContestStandingsTableImpl("", "excluded", ""),
	}
}

func newContestStandingsTableImpl(schemaName, tableName, alias string) contestStandingsTable {
	var (
		ContestIDColumn = postgres.StringColumn("contest_id")
		UserIDColumn    = postgres.StringColumn("user_id")
		ScoreColumn     = postgres.IntegerColumn("score")
		allColumns      = postgres.ColumnList{ContestIDColumn, UserIDColumn, ScoreColumn}
		mutableColumns  = postgres.ColumnList{ScoreColumn}
		defaultColumns  = postgres.ColumnList{}
	)

	return contestStandingsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ContestID: ContestIDColumn,
		UserID:    UserIDColumn,
		Score:     ScoreColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
