//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Countries = newCountriesTable("public", "countries", "")

type countriesTable struct {
	postgres.Table

	// Columns
	ID       postgres.ColumnString
	Code     postgres.ColumnString
	FullName postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CountriesTable struct {
	countriesTable

	EXCLUDED countriesTable
}

// AS creates new CountriesTable with assigned alias
func (a CountriesTable) AS(alias string) *CountriesTable {
	return newCountriesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CountriesTable with assigned schema name
func (a CountriesTable) FromSchema(schemaName string) *CountriesTable {
	return newCountriesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CountriesTable with assigned table prefix
func (a CountriesTable) WithPrefix(prefix string) *CountriesTable {
	return newCountriesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CountriesTable with assigned table suffix
func (a CountriesTable) WithSuffix(suffix string) *CountriesTable {
	return newCountriesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCountriesTable(schemaName, tableName, alias string) *CountriesTable {
	return &CountriesTable{
		countriesTable: newCountriesTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newCountriesTableImpl("", "excluded", ""),
	}
}

func newCountriesTableImpl(schemaName, tableName, alias string) countriesTable {
	var (
		IDColumn       = postgres.StringColumn("id")
		CodeColumn     = postgres.StringColumn("code")
		FullNameColumn = postgres.StringColumn("full_name")
		allColumns     = postgres.ColumnList{IDColumn, CodeColumn, FullNameColumn}
		mutableColumns = postgres.ColumnList{CodeColumn, FullNameColumn}
		defaultColumns = postgres.ColumnList{IDColumn}
	)

	return countriesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:       IDColumn,
		Code:     CodeColumn,
		FullName: FullNameColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
