//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var GroupPicks = newGroupPicksTable("public", "group_picks", "")

type groupPicksTable struct {
	postgres.Table

	// Columns
	UserID    postgres.ColumnString
	ContestID postgres.ColumnString
	CountryID postgres.ColumnString
	Place     postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type GroupPicksTable struct {
	groupPicksTable

	EXCLUDED groupPicksTable
}

// AS creates new GroupPicksTable with assigned alias
func (a GroupPicksTable) AS(alias string) *GroupPicksTable {
	return newGroupPicksTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new GroupPicksTable with assigned schema name
func (a GroupPicksTable) FromSchema(schemaName string) *GroupPicksTable {
	return newGroupPicksTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new GroupPicksTable with assigned table prefix
func (a GroupPicksTable) WithPrefix(prefix string) *GroupPicksTable {
	return newGroupPicksTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new GroupPicksTable with assigned table suffix
func (a GroupPicksTable) WithSuffix(suffix string) *GroupPicksTable {
	return newGroupPicksTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newGroupPicksTable(schemaName, tableName, alias string) *GroupPicksTable {
	return &GroupPicksTable{
		groupPicksTable: newGroupPicksTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newGroupPicksTableImpl("", "excluded", ""),
	}
}

func newGroupPicksTableImpl(schemaName, tableName, alias string) groupPicksTable {
	var (
		UserIDColumn    = postgres.StringColumn("user_id")
		ContestIDColumn = postgres.StringColumn("contest_id")
		CountryIDColumn = postgres.StringColumn("country_id")
		PlaceColumn     = postgres.IntegerColumn("place")
		allColumns      = postgres.ColumnList{UserIDColumn, ContestIDColumn, CountryIDColumn, PlaceColumn}
		mutableColumns  = postgres.ColumnList{PlaceColumn}
		defaultColumns  = postgres.ColumnList{}
	)

	return groupPicksTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:    UserIDColumn,
		ContestID: ContestIDColumn,
		CountryID: CountryIDColumn,
		Place:     PlaceColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
