//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var GroupStandings = newGroupStandingsTable("public", "group_standings", "")

type groupStandingsTable struct {
	postgres.Table

	// Columns
	ContestID postgres.ColumnString
	CountryID postgres.ColumnString
	Letter    postgres.ColumnString
	Points    postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type GroupStandingsTable struct {
	groupStandingsTable

	EXCLUDED groupStandingsTable
}

// AS creates new GroupStandingsTable with assigned alias
func (a GroupStandingsTable) AS(alias string) *GroupStandingsTable {
	return newGroupStandingsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new GroupStandingsTable with assigned schema name
func (a GroupStandingsTable) FromSchema(schemaName string) *GroupStandingsTable {
	return newGroupStandingsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new GroupStandingsTable with assigned table prefix
func (a GroupStandingsTable) WithPrefix(prefix string) *GroupStandingsTable {
	return newGroupStandingsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new GroupStandingsTable with assigned table suffix
func (a GroupStandingsTable) WithSuffix(suffix string) *GroupStandingsTable {
	return newGroupStandingsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newGroupStandingsTable(schemaName, tableName, alias string) *GroupStandingsTable {
	return &GroupStandingsTable{
		groupStandingsTable: newGroupStandingsTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newGroupStandingsTableImpl("", "excluded", ""),
	}
}

func newGroupStandingsTableImpl(schemaName, tableName, alias string) groupStandingsTable {
	var (
		ContestIDColumn = postgres.StringColumn("contest_id")
		CountryIDColumn = postgres.StringColumn("country_id")
		LetterColumn    = postgres.StringColumn("letter")
		PointsColumn    = postgres.IntegerColumn("points")
		allColumns      = postgres.ColumnList{ContestIDColumn, CountryIDColumn, LetterColumn, PointsColumn}
		mutableColumns  = postgres.ColumnList{LetterColumn, PointsColumn}
		defaultColumns  = postgres.ColumnList{PointsColumn}
	)

	return groupStandingsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ContestID: ContestIDColumn,
		CountryID: CountryIDColumn,
		Letter:    LetterColumn,
		Points:    PointsColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
