//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var KnockoutStandings = newKnockoutStandingsTable("public", "knockout_standings", "")

type knockoutStandingsTable struct {
	postgres.Table

	// Columns
	ContestID postgres.ColumnString
	CountryID postgres.ColumnString
	Round     postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type KnockoutStandingsTable struct {
	knockoutStandingsTable

	EXCLUDED knockoutStandingsTable
}

// AS creates new KnockoutStandingsTable with assigned alias
func (a KnockoutStandingsTable) AS(alias string) *KnockoutStandingsTable {
	return newKnockoutStandingsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new KnockoutStandingsTable with assigned schema name
func (a KnockoutStandingsTable) FromSchema(schemaName string) *KnockoutStandingsTable {
	return newKnockoutStandingsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new KnockoutStandingsTable with assigned table prefix
func (a KnockoutStandingsTable) WithPrefix(prefix string) *KnockoutStandingsTable {
	return newKnockoutStandingsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new KnockoutStandingsTable with assigned table suffix
func (a KnockoutStandingsTable) WithSuffix(suffix string) *KnockoutStandingsTable {
	return newKnockoutStandingsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newKnockoutStandingsTable(schemaName, tableName, alias string) *KnockoutStandingsTable {
	return &KnockoutStandingsTable{
		knockoutStandingsTable: newKnockoutStandingsTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newKnockoutStandingsTableImpl("", "excluded", ""),
	}
}

func newKnockoutStandingsTableImpl(schemaName, tableName, alias string) knockoutStandingsTable {
	var (
		ContestIDColumn = postgres.StringColumn("contest_id")
		CountryIDColumn = postgres.StringColumn("country_id")
		RoundColumn     = postgres.IntegerColumn("round")
		allColumns      = postgres.ColumnList{ContestIDColumn, CountryIDColumn, RoundColumn}
		mutableColumns  = postgres.ColumnList{RoundColumn}
		defaultColumns  = postgres.ColumnList{}
	)

	return knockoutStandingsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ContestID: ContestIDColumn,
		CountryID: CountryIDColumn,
		Round:     RoundColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
