//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var KnockoutPicks = newKnockoutPicksTable("public", "knockout_picks", "")

type knockoutPicksTable struct {
	postgres.Table

	// Columns
	UserID    postgres.ColumnString
	ContestID postgres.ColumnString
	CountryID postgres.ColumnString
	Round     postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type KnockoutPicksTable struct {
	knockoutPicksTable

	EXCLUDED knockoutPicksTable
}

// AS creates new KnockoutPicksTable with assigned alias
func (a KnockoutPicksTable) AS(alias string) *KnockoutPicksTable {
	return newKnockoutPicksTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new KnockoutPicksTable with assigned schema name
func (a KnockoutPicksTable) FromSchema(schemaName string) *KnockoutPicksTable {
	return newKnockoutPicksTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new KnockoutPicksTable with assigned table prefix
func (a KnockoutPicksTable) WithPrefix(prefix string) *KnockoutPicksTable {
	return newKnockoutPicksTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new KnockoutPicksTable with assigned table suffix
func (a KnockoutPicksTable) WithSuffix(suffix string) *KnockoutPicksTable {
	return newKnockoutPicksTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newKnockoutPicksTable(schemaName, tableName, alias string) *KnockoutPicksTable {
	return &KnockoutPicksTable{
		knockoutPicksTable: newKnockoutPicksTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newKnockoutPicksTableImpl("", "excluded", ""),
	}
}

func newKnockoutPicksTableImpl(schemaName, tableName, alias string) knockoutPicksTable {
	var (
		UserIDColumn    = postgres.StringColumn("user_id")
		ContestIDColumn = postgres.StringColumn("contest_id")
		CountryIDColumn = postgres.StringColumn("country_id")
		RoundColumn     = postgres.IntegerColumn("round")
		allColumns      = postgres.ColumnList{UserIDColumn, ContestIDColumn, CountryIDColumn, RoundColumn}
		mutableColumns  = postgres.ColumnList{RoundColumn}
		defaultColumns  = postgres.ColumnList{}
	)

	return knockoutPicksTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:    UserIDColumn,
		ContestID: ContestIDColumn,
		CountryID: CountryIDColumn,
		Round:     RoundColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
