//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Matches = newMatchesTable("public", "matches", "")

type matchesTable struct {
	postgres.Table

	// Columns
	ID                postgres.ColumnString
	ContestID         postgres.ColumnString
	Country1ID        postgres.ColumnString
	Country2ID        postgres.ColumnString
	Country1Goals     postgres.ColumnInteger
	Country2Goals     postgres.ColumnInteger
	Country1Penalties postgres.ColumnInteger
	Country2Penalties postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type MatchesTable struct {
	matchesTable

	EXCLUDED matchesTable
}

// AS creates new MatchesTable with assigned alias
func (a MatchesTable) AS(alias string) *MatchesTable {
	return newMatchesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MatchesTable with assigned schema name
func (a MatchesTable) FromSchema(schemaName string) *MatchesTable {
	return newMatchesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MatchesTable with assigned table prefix
func (a MatchesTable) WithPrefix(prefix string) *MatchesTable {
	return newMatchesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MatchesTable with assigned table suffix
func (a MatchesTable) WithSuffix(suffix string) *MatchesTable {
	return newMatchesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMatchesTable(schemaName, tableName, alias string) *MatchesTable {
	return &MatchesTable{
		matchesTable: newMatchesTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newMatchesTableImpl("", "excluded", ""),
	}
}

func newMatchesTableImpl(schemaName, tableName, alias string) matchesTable {
	var (
		IDColumn                = postgres.StringColumn("id")
		ContestIDColumn         = postgres.StringColumn("contest_id")
		Country1IDColumn        = postgres.StringColumn("country1_id")
		Country2IDColumn        = postgres.StringColumn("country2_id")
		Country1GoalsColumn     = postgres.IntegerColumn("country1_goals")
		Country2GoalsColumn     = postgres.IntegerColumn("country2_goals")
		Country1PenaltiesColumn = postgres.IntegerColumn("country1_penalties")
		Country2PenaltiesColumn = postgres.IntegerColumn("country2_penalties")
		allColumns              = postgres.ColumnList{IDColumn, ContestIDColumn, Country1IDColumn, Country2IDColumn, Country1GoalsColumn, Country2GoalsColumn, Country1PenaltiesColumn, Country2PenaltiesColumn}
		mutableColumns          = postgres.ColumnList{ContestIDColumn, Country1IDColumn, Country2IDColumn, Country1GoalsColumn, Country2GoalsColumn, Country1PenaltiesColumn, Country2PenaltiesColumn}
		defaultColumns          = postgres.ColumnList{IDColumn}
	)

	return matchesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                IDColumn,
		ContestID:         ContestIDColumn,
		Country1ID:        Country1IDColumn,
		Country2ID:        Country2IDColumn,
		Country1Goals:     Country1GoalsColumn,
		Country2Goals:     Country2GoalsColumn,
		Country1Penalties: Country1PenaltiesColumn,
		Country2Penalties: Country2PenaltiesColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
