//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SubcontestEntries = newSubcontestEntriesTable("public", "subcontest_entries", "")

type subcontestEntriesTable struct {
	postgres.Table

	// Columns
	SubcontestID postgres.ColumnString
	UserID       postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type SubcontestEntriesTable struct {
	subcontestEntriesTable

	EXCLUDED subcontestEntriesTable
}

// AS creates new SubcontestEntriesTable with assigned alias
func (a SubcontestEntriesTable) AS(alias string) *SubcontestEntriesTable {
	return newSubcontestEntriesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SubcontestEntriesTable with assigned schema name
func (a SubcontestEntriesTable) FromSchema(schemaName string) *SubcontestEntriesTable {
	return newSubcontestEntriesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SubcontestEntriesTable with assigned table prefix
func (a SubcontestEntriesTable) WithPrefix(prefix string) *SubcontestEntriesTable {
	return newSubcontestEntriesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SubcontestEntriesTable with assigned table suffix
func (a SubcontestEntriesTable) WithSuffix(suffix string) *SubcontestEntriesTable {
	return newSubcontestEntriesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSubcontestEntriesTable(schemaName, tableName, alias string) *SubcontestEntriesTable {
	return &SubcontestEntriesTable{
		subcontestEntriesTable: newSubcontestEntriesTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newSubcontestEntriesTableImpl("", "excluded", ""),
	}
}

func newSubcontestEntriesTableImpl(schemaName, tableName, alias string) subcontestEntriesTable {
	var (
		SubcontestIDColumn = postgres.StringColumn("subcontest_id")
		UserIDColumn       = postgres.StringColumn("user_id")
		allColumns         = postgres.ColumnList{SubcontestIDColumn, UserIDColumn}
		mutableColumns     = postgres.ColumnList{}
		defaultColumns     = postgres.ColumnList{}
	)

	return subcontestEntriesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		SubcontestID: SubcontestIDColumn,
		UserID:       UserIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
