//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Subcontests = newSubcontestsTable("public", "subcontests", "")

type subcontestsTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	ContestID postgres.ColumnString
	UserID    postgres.ColumnString
	JoinCode  postgres.ColumnString
	Title     postgres.ColumnString
	Slug      postgres.ColumnString
	DeletedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type SubcontestsTable struct {
	subcontestsTable

	EXCLUDED subcontestsTable
}

// AS creates new SubcontestsTable with assigned alias
func (a SubcontestsTable) AS(alias string) *SubcontestsTable {
	return newSubcontestsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SubcontestsTable with assigned schema name
func (a SubcontestsTable) FromSchema(schemaName string) *SubcontestsTable {
	return newSubcontestsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SubcontestsTable with assigned table prefix
func (a SubcontestsTable) WithPrefix(prefix string) *SubcontestsTable {
	return newSubcontestsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SubcontestsTable with assigned table suffix
func (a SubcontestsTable) WithSuffix(suffix string) *SubcontestsTable {
	return newSubcontestsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSubcontestsTable(schemaName, tableName, alias string) *SubcontestsTable {
	return &SubcontestsTable{
		subcontestsTable: newSubcontestsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newSubcontestsTableImpl("", "excluded", ""),
	}
}

func newSubcontestsTableImpl(schemaName, tableName, alias string) subcontestsTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		ContestIDColumn = postgres.StringColumn("contest_id")
		UserIDColumn    = postgres.StringColumn("user_id")
		JoinCodeColumn  = postgres.StringColumn("join_code")
		TitleColumn     = postgres.StringColumn("title")
		SlugColumn      = postgres.StringColumn("slug")
		DeletedAtColumn = postgres.TimestampzColumn("deleted_at")
		allColumns      = postgres.ColumnList{IDColumn, ContestIDColumn, UserIDColumn, JoinCodeColumn, TitleColumn, SlugColumn, DeletedAtColumn}
		mutableColumns  = postgres.ColumnList{ContestIDColumn, UserIDColumn, JoinCodeColumn, TitleColumn, SlugColumn, DeletedAtColumn}
		defaultColumns  = postgres.ColumnList{IDColumn}
	)

	return subcontestsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		ContestID: ContestIDColumn,
		UserID:    UserIDColumn,
		JoinCode:  JoinCodeColumn,
		Title:     TitleColumn,
		Slug:      SlugColumn,
		DeletedAt: DeletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
