//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	ContestStandings = ContestStandings.FromSchema(schema)
	Contests = Contests.FromSchema(schema)
	Countries = Countries.FromSchema(schema)
	GroupPicks = GroupPicks.FromSchema(schema)
	GroupStandings = GroupStandings.FromSchema(schema)
	KnockoutPicks = KnockoutPicks.FromSchema(schema)
	KnockoutStandings = KnockoutStandings.FromSchema(schema)
	Matches = Matches.FromSchema(schema)
	SubcontestEntries = SubcontestEntries.FromSchema(schema)
	Subcontests = Subcontests.FromSchema(schema)
	Users = Users.FromSchema(schema)
}
